defaults:
  - env: env_config.yaml
  - agent: ddpg

# mode
reward_free: false
# task settings (currently ignored)
task: ""

domain: particle
ds_task: "poison_l"
factored: false
n_env: 1


obs_type: states # [states, pixels]
frame_stack: 3 # only works if obs_type=pixels
action_repeat: 1 # set to 2 for pixels
discount: 0.99
# train settings
num_train_frames: 2000010
num_seed_frames: 4000
# eval
eval_every_frames: 10000
num_eval_episodes: 0
# pretrained
snapshot_ts: 0 # 100000
snapshot_base_dir: ./pretrained_models
# replay buffer
replay_buffer_size: 1000000
replay_buffer_num_workers: 4
batch_size: ${agent.batch_size}
nstep: ${agent.nstep}
update_encoder: false # can be either true or false depending if we want to fine-tune encoder
# misc
seed: 1
device: cuda
cuda_id: 0
save_video: false
save_train_video: false
use_tb: false
use_wandb: true
# experiment
experiment:
  ${agent.name}
  ${domain}
  ds:${ds_task}
  ${seed}


hydra:
  run:
    dir: ./exp_local/${now:%Y.%m.%d}/${now:%H%M%S}_${agent.name}
  sweep:
    dir: ./exp_sweep/${now:%Y.%m.%d}/${now:%H%M}_${agent.name}_${experiment}
    subdir: ${hydra.job.num}
